package org.skitts.towa

val TOWA_DICT_CODE_MAP_EN: HashMap<String, String> = hashMapOf(
    "bra" to "Brazilian",
    "hob" to "Hokkaido-ben",
    "ksb" to "Kansai-ben",
    "ktb" to "Kantou-ben",
    "kyb" to "Kyoto-ben",
    "kyu" to "Kyuushuu-ben",
    "nab" to "Nagano-ben",
    "osb" to "Osaka-ben",
    "rkb" to "Ryuukyuu-ben",
    "thb" to "Touhoku-ben",
    "tsb" to "Tosa-ben",
    "tsug" to "Tsugaru-ben",
    "agric" to "agriculture",
    "anat" to "anatomy",
    "archeol" to "archeology",
    "archit" to "architecture",
    "art" to "art, aesthetics",
    "astron" to "astronomy",
    "audvid" to "audiovisual",
    "aviat" to "aviation",
    "baseb" to "baseball",
    "biochem" to "biochemistry",
    "biol" to "biology",
    "bot" to "botany",
    "boxing" to "boxing",
    "Buddh" to "Buddhism",
    "bus" to "business",
    "cards" to "card games",
    "chem" to "chemistry",
    "chmyth" to "Chinese mythology",
    "Christn" to "Christianity",
    "civeng" to "civil engineering",
    "cloth" to "clothing",
    "comp" to "computing",
    "cryst" to "crystallography",
    "dent" to "dentistry",
    "ecol" to "ecology",
    "econ" to "economics",
    "elec" to "electricity, elec. eng.",
    "electr" to "electronics",
    "embryo" to "embryology",
    "engr" to "engineering",
    "ent" to "entomology",
    "figskt" to "figure skating",
    "film" to "film",
    "finc" to "finance",
    "fish" to "fishing",
    "food" to "food, cooking",
    "gardn" to "gardening, horticulture",
    "genet" to "genetics",
    "geogr" to "geography",
    "geol" to "geology",
    "geom" to "geometry",
    "go" to "go (game)",
    "golf" to "golf",
    "gramm" to "grammar",
    "grmyth" to "Greek mythology",
    "hanaf" to "hanafuda",
    "horse" to "horse racing",
    "internet" to "Internet",
    "jpmyth" to "Japanese mythology",
    "kabuki" to "kabuki",
    "law" to "law",
    "ling" to "linguistics",
    "logic" to "logic",
    "MA" to "martial arts",
    "mahj" to "mahjong",
    "manga" to "manga",
    "math" to "mathematics",
    "mech" to "mechanical engineering",
    "med" to "medicine",
    "met" to "meteorology",
    "mil" to "military",
    "min" to "mineralogy",
    "mining" to "mining",
    "motor" to "motorsport",
    "music" to "music",
    "noh" to "noh",
    "ornith" to "ornithology",
    "paleo" to "paleontology",
    "pathol" to "pathology",
    "pharm" to "pharmacology",
    "phil" to "philosophy",
    "photo" to "photography",
    "physics" to "physics",
    "physiol" to "physiology",
    "politics" to "politics",
    "print" to "printing",
    "prowres" to "professional wrestling",
    "psy" to "psychiatry",
    "psyanal" to "psychoanalysis",
    "psych" to "psychology",
    "rail" to "railway",
    "rommyth" to "Roman mythology",
    "Shinto" to "Shinto",
    "shogi" to "shogi",
    "ski" to "skiing",
    "sports" to "sports",
    "stat" to "statistics",
    "stockm" to "stock market",
    "sumo" to "sumo",
    "surg" to "surgery",
    "telec" to "telecommunications",
    "tradem" to "trademark",
    "tv" to "television",
    "vet" to "veterinary terms",
    "vidg" to "video games",
    "zool" to "zoology",
    "ateji" to "ateji (phonetic) reading",
    "ik" to "word containing irregular kana usage",
    "iK" to "word containing irregular kanji usage",
    "io" to "irregular okurigana usage",
    "oK" to "word containing out-dated kanji or kanji usage",
    "rK" to "rarely used kanji form",
    "sK" to "search-only kanji form",
    "abbr" to "abbreviation",
    "arch" to "archaic",
    "char" to "character",
    "chn" to "children's language",
    "col" to "colloquial",
    "company" to "company name",
    "creat" to "creature",
    "dated" to "dated term",
    "dei" to "deity",
    "derog" to "derogatory",
    "doc" to "document",
    "euph" to "euphemistic",
    "ev" to "event",
    "fam" to "familiar language",
    "fem" to "female term or language",
    "fict" to "fiction",
    "form" to "formal or literary term",
    "given" to "given name or forename, gender not specified",
    "group" to "group",
    "hist" to "historical term",
    "hon" to "honorific or respectful (sonkeigo) language",
    "hum" to "humble (kenjougo) language",
    "id" to "idiomatic expression",
    "joc" to "jocular, humorous term",
    "leg" to "legend",
    "m-sl" to "manga slang",
    "male" to "male term or language",
    "myth" to "mythology",
    "net-sl" to "Internet slang",
    "obj" to "object",
    "obs" to "obsolete term",
    "on-mim" to "onomatopoeic or mimetic word",
    "organization" to "organization name",
    "oth" to "other",
    "person" to "full name of a particular person",
    "place" to "place name",
    "poet" to "poetical term",
    "pol" to "polite (teineigo) language",
    "product" to "product name",
    "proverb" to "proverb",
    "quote" to "quotation",
    "rare" to "rare term",
    "relig" to "religion",
    "sens" to "sensitive",
    "serv" to "service",
    "ship" to "ship name",
    "sl" to "slang",
    "station" to "railway station",
    "surname" to "family or surname",
    "uk" to "word usually written using kana alone",
    "unclass" to "unclassified name",
    "vulg" to "vulgar expression or word",
    "work" to "work of art, literature, music, etc. name",
    "X" to "rude or X-rated term (not displayed in educational software)",
    "yoji" to "yojijukugo",
    "adj-f"     to "Prenominal Noun/Verb", //"noun or verb acting prenominally", // (連体修飾語 / 連体修飾節)
    "adj-i"     to "～い Adj.", //"adjective (keiyoushi)",
    "adj-ix"    to "～(良)い Adj.", //"adjective (keiyoushi) - yoi/ii class",
    "adj-kari"  to "～かり Adj. (arch.)", //"'kari' adjective (archaic)",
    "adj-ku"    to "～く Adj. (arch.)", //"'ku' adjective (archaic)",
    "adj-na"    to "～な Adj.", //"adjectival nouns or quasi-adjectives (keiyodoshi)",
    "adj-nari"  to "～なり Adj.", //"archaic/formal form of na-adjective",
    "adj-no"    to "～の Adj.", //"nouns which may take the genitive case particle 'no'",
    "adj-pn"    to "Pre-N. Adj.", //"pre-noun adjectival (rentaishi)",
    "adj-shiku" to "～しく Adj.", //"'shiku' adjective (archaic)",
    "adj-t"     to "～たる Adj.", //"'taru' adjective",
    "adv"       to "Adv.", //"adverb (fukushi)",
    "adv-to"    to "～と Adv.", //"adverb taking the 'to' particle",
    "aux"       to "auxiliary",
    "aux-adj"   to "auxiliary adjective",
    "aux-v"     to "auxiliary verb",
    "conj"      to "conjunction",
    "cop"       to "Copula", //"copula",
    "ctr"       to "Counter", //"counter",
    "exp"       to "Expression", //"expressions (phrases, clauses, etc.)",
    "int"       to "Interjection", //"interjection (kandoushi)",
    "n"         to "Noun", //"noun (common) (futsuumeishi)",
    "n-adv"     to "Adverbial Noun", //"adverbial noun (fukushitekimeishi)",
    "n-pr"      to "Proper Noun", //"proper noun",
    "n-pref"    to "Noun Prefix", //"noun, used as a prefix",
    "n-suf"     to "Noun Suffix", //"noun, used as a suffix",
    "n-t"       to "Temporal Noun", //"noun (temporal) (jisoumeishi)",
    "num"       to "Numeric", //"numeric",
    "pn"        to "Pronoun", //"pronoun",
    "pref"      to "Prefix", //"prefix",
    "prt"       to "Particle", //"particle",
    "suf"       to "Suffix", //"suffix",
    "unc"       to "unclassified",
    "v-unspec"  to "verb unspecified",
    "v1"        to "Ichidan Verb", //"Ichidan verb",
    "v1-s"      to "Ichidan Verb (～くれる)", //"Ichidan verb - kureru special class",
    "v2a-s"     to "Nidan Verb (arch.)", //"Nidan verb with 'u' ending (archaic)",
    "v2b-k"     to "Nidan Verb (arch.)", //"Nidan verb (upper class) with 'bu' ending (archaic)",
    "v2b-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'bu' ending (archaic)",
    "v2d-k"     to "Nidan Verb (arch.)", //"Nidan verb (upper class) with 'dzu' ending (archaic)",
    "v2d-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'dzu' ending (archaic)",
    "v2g-k"     to "Nidan Verb (arch.)", //"Nidan verb (upper class) with 'gu' ending (archaic)",
    "v2g-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'gu' ending (archaic)",
    "v2h-k"     to "Nidan Verb (arch.)", //"Nidan verb (upper class) with 'hu/fu' ending (archaic)",
    "v2h-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'hu/fu' ending (archaic)",
    "v2k-k"     to "Nidan Verb (arch.)", //"Nidan verb (upper class) with 'ku' ending (archaic)",
    "v2k-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'ku' ending (archaic)",
    "v2m-k"     to "Nidan Verb (arch.)", //"Nidan verb (upper class) with 'mu' ending (archaic)",
    "v2m-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'mu' ending (archaic)",
    "v2n-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'nu' ending (archaic)",
    "v2r-k"     to "Nidan Verb (arch.)", //"Nidan verb (upper class) with 'ru' ending (archaic)",
    "v2r-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'ru' ending (archaic)",
    "v2s-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'su' ending (archaic)",
    "v2t-k"     to "Nidan Verb (arch.)", //"Nidan verb (upper class) with 'tsu' ending (archaic)",
    "v2t-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'tsu' ending (archaic)",
    "v2w-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)",
    "v2y-k"     to "Nidan Verb (arch.)", //"Nidan verb (upper class) with 'yu' ending (archaic)",
    "v2y-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'yu' ending (archaic)",
    "v2z-s"     to "Nidan Verb (arch.)", //"Nidan verb (lower class) with 'zu' ending (archaic)",
    "v4b"       to "Yodan Verb (arch.)", //"Yodan verb with 'bu' ending (archaic)",
    "v4g"       to "Yodan Verb (arch.)", //"Yodan verb with 'gu' ending (archaic)",
    "v4h"       to "Yodan Verb (arch.)", //"Yodan verb with 'hu/fu' ending (archaic)",
    "v4k"       to "Yodan Verb (arch.)", //"Yodan verb with 'ku' ending (archaic)",
    "v4m"       to "Yodan Verb (arch.)", //"Yodan verb with 'mu' ending (archaic)",
    "v4n"       to "Yodan Verb (arch.)", //"Yodan verb with 'nu' ending (archaic)",
    "v4r"       to "Yodan Verb (arch.)", //"Yodan verb with 'ru' ending (archaic)",
    "v4s"       to "Yodan Verb (arch.)", //"Yodan verb with 'su' ending (archaic)",
    "v4t"       to "Yodan Verb (arch.)", //"Yodan verb with 'tsu' ending (archaic)",
    "v5aru"     to "Godan Verb", //"Godan verb - -aru special class",
    "v5b"       to "Godan Verb", //"Godan verb with 'bu' ending",
    "v5g"       to "Godan Verb", //"Godan verb with 'gu' ending",
    "v5k"       to "Godan Verb", //"Godan verb with 'ku' ending",
    "v5k-s"     to "Godan Verb (～行く)", //"Godan verb - Iku/Yuku special class",
    "v5m"       to "Godan Verb", //"Godan verb with 'mu' ending",
    "v5n"       to "Godan Verb", //"Godan verb with 'nu' ending",
    "v5r"       to "Godan Verb", //"Godan verb with 'ru' ending",
    "v5r-i"     to "Irregular Godan V.", //"Godan verb with 'ru' ending (irregular verb)",
    "v5s"       to "Godan Verb", //"Godan verb with 'su' ending",
    "v5t"       to "Godan Verb", //"Godan verb with 'tsu' ending",
    "v5u"       to "Godan Verb", //"Godan verb with 'u' ending",
    "v5u-s"     to "Godan Verb", //"Godan verb with 'u' ending (special class)",
    "v5uru"     to "Godan Verb", //"Godan verb - Uru old class verb (old form of Eru)",
    "vi"        to "Intransitive", //"intransitive verb",
    "vk"        to "Kuru verb - special class",
    "vn"        to "Irregular ～ぬ V.", //"irregular nu verb",
    "vr"        to "Irregular ～る V. (～り plain form)", //"irregular ru verb, plain form ends with -ri",
    "vs"        to "Verbal Noun (～する)", //"noun or participle which takes the aux. verb suru",
    "vs-c"      to "～す Verb", //"su verb - precursor to the modern suru",
    "vs-i"      to "～する Verb", //"suru verb - included",
    "vs-s"      to "～する Verb (Irregular Conj.)", //"suru verb - special class", // サ行変格活用
    "vt"        to "Transitive", //"transitive verb",
    "vz"        to "～ずる Verb (～じる Alt. Form)", //"Ichidan verb - zuru verb (alternative form of -jiru verbs)",
    "gikun" to "gikun (meaning as reading) or jukujikun (special kanji reading)",
    "ik" to "word containing irregular kana usage",
    "ok" to "out-dated or obsolete kana usage",
    "rk" to "rarely used kana form",
    "sk" to "search-only kana form"
)

val TOWA_DICT_CODE_MAP_JP: HashMap<String, String> =  hashMapOf(

)

fun code2en(code: String): String {
    return TOWA_DICT_CODE_MAP_EN[code] ?: code
}

fun code2jp(code: String): String {
    return TOWA_DICT_CODE_MAP_JP[code] ?: code
}